name: Sync Labels

on:
  push:
    paths:
      - ".github/workflows/sync-labels.yml"
      - ".github/labels.yml"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-22.04
    env:
      LABEL_SYNC_TOKEN: ${{ secrets.LABEL_SYNC_TOKEN }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/labels.yml
          sparse-checkout-cone-mode: false
      - run: npx github-label-sync -a '${{ secrets.LABEL_SYNC_TOKEN }}' -l '.github/labels.yml' ${{ github.repository }}
        if: env.LABEL_SYNC_TOKEN != null
